/**
 * Container tags are generated by the supermemory plugin as
 * `repo_<sanitized-name>__<sha256(normalized-remote).slice(0, 16)>`, so the
 * project name is already inside the tag and needs no lookup.
 *
 * See the resolution on https://github.com/cinjoff/firehorse/issues/90 —
 * the derivation is reproduced there against this repo's own tag.
 */

const GENERATED_TAG = /^repo_(.+)__([0-9a-f]{16})$/;

export interface ParsedContainerTag {
  /** The tag exactly as supermemory stores it. */
  readonly tag: string;
  /** A name to show a human. Falls back to the raw tag when unparseable. */
  readonly name: string;
  /** The identity hash, when the tag is a generated one. */
  readonly hash: string | undefined;
  /** False for hand-set tags, which do not carry a name. */
  readonly generated: boolean;
}

/**
 * `sanitizeRepoName` is lossy — it lowercases and collapses every character
 * outside `[a-z0-9]` to `_` — so the name recovered here is the sanitized
 * form, not necessarily the repo's real spelling.
 */
export function parseContainerTag(tag: string): ParsedContainerTag {
  const match = GENERATED_TAG.exec(tag);

  if (!match) {
    return { tag, name: tag, hash: undefined, generated: false };
  }

  const [, name, hash] = match;

  // The regex guarantees both groups, but noUncheckedIndexedAccess does not know that.
  if (!name || !hash) {
    return { tag, name: tag, hash: undefined, generated: false };
  }

  return { tag, name, hash, generated: true };
}
