#!/usr/bin/env python3
"""Regenerate catalog.md from data/implementations.json.

catalog.md is generated. Edit the JSON (or re-run classify.py), then run this.
Narrative docs in this directory are hand-written and are never touched here.

Usage:
    python3 docs/research/jev/render.py
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

HERE = Path(__file__).parent
DATA = HERE / "data" / "implementations.json"
OUT = HERE / "catalog.md"

CATEGORY_ORDER = [
    "agent-guardrail",
    "agent-routing",
    "context-engineering",
    "dev-tooling",
    "browser-computer-use",
    "data-retrieval",
    "domain-app",
    "open-reproduction",
    "evaluation",
    "games-robotics",
    "media-creative",
]

TITLES = {
    "agent-guardrail": "Agent guardrails",
    "agent-routing": "Agent and model routing",
    "context-engineering": "Context engineering",
    "dev-tooling": "SDKs, clients, and developer tooling",
    "browser-computer-use": "Browser and computer use",
    "data-retrieval": "Data, search, and retrieval",
    "domain-app": "Domain applications",
    "open-reproduction": "Open reproductions",
    "evaluation": "Evaluation and calibration",
    "games-robotics": "Games, simulation, and robotics",
    "media-creative": "Media and creative",
}

ROLE_GLYPH = {"gate": "gate", "select": "select", "rank": "rank", "label": "label", "none": "-"}


def stars(n: int | None) -> str:
    if not n:
        return "0"
    return f"{n / 1000:.1f}k" if n >= 1000 else str(n)


def clean(text: str, limit: int = 155) -> str:
    text = " ".join((text or "").split()).replace("|", "/")
    return text[: limit - 1] + "…" if len(text) > limit else text


def main() -> int:
    repos = json.loads(DATA.read_text())
    verified = {k: v for k, v in repos.items() if v["jev"]["verified_integration"]}
    listed_only = {
        k: v
        for k, v in repos.items()
        if v["jev"]["in_ecosystem"] and not v["jev"]["verified_integration"]
    }
    excluded = {k: v for k, v in repos.items() if not v["jev"]["in_ecosystem"]}

    by_cat = Counter(v["jev"]["category"] for v in verified.values())
    generated = max(
        (v["jev"]["classified_at"] for v in repos.values() if "jev" in v), default="unknown"
    )

    lines: list[str] = [
        "# Jev implementation catalog",
        "",
        "Generated by `render.py` from `data/implementations.json`. Do not hand-edit.",
        "To refresh, see [how to enrich this](README.md#how-to-enrich-this).",
        "",
        f"Last classified: {generated}. "
        f"{len(repos)} repositories collected, {len(verified)} with a verified Jev integration, "
        f"{len(listed_only)} listed without one, {len(excluded)} excluded as unrelated.",
        "",
        "Columns: stars are live at collection time. **Role** is what Jev itself does in the "
        "project (`gate`, `select`, `rank`, `label`). **Code owns** is the model's estimate that "
        "deterministic code still decides what executes. A `?` marks a row the classifier was "
        "not confident about; treat those as unreviewed.",
        "",
        "## Contents",
        "",
    ]
    for cat in CATEGORY_ORDER:
        if by_cat.get(cat):
            lines.append(f"- [{TITLES[cat]}](#{TITLES[cat].lower().replace(' ', '-').replace(',', '')}) ({by_cat[cat]})")
    lines += ["", "---", ""]

    for cat in CATEGORY_ORDER:
        rows = sorted(
            ((k, v) for k, v in verified.items() if v["jev"]["category"] == cat),
            key=lambda kv: -(kv[1]["stars"] or 0),
        )
        if not rows:
            continue
        lines += [
            f"## {TITLES[cat]}",
            "",
            f"{len(rows)} projects. "
            f"{sum(1 for _, v in rows if v['jev']['agentic_dev'] >= 0.5)} are aimed at agentic "
            "development workflows.",
            "",
            "| Repository | Stars | Role | Code owns | What it does |",
            "|---|---:|---|---:|---|",
        ]
        for key, rec in rows:
            j = rec["jev"]
            flag = " ?" if j["needs_review"] else ""
            desc = clean(rec.get("desc") or rec.get("gh_desc") or "")
            lines.append(
                f"| [{key}](https://github.com/{key}) | {stars(rec.get('stars'))} | "
                f"{ROLE_GLYPH.get(j['jev_role'], '-')}{flag} | {j['code_owns_control']:.2f} | {desc} |"
            )
        lines.append("")

    if listed_only:
        lines += [
            "---",
            "",
            "## Listed without a verified integration",
            "",
            "These appear in community lists and are plausibly adjacent, but their own "
            "description does not show Jev being called. Several are aspirational "
            '("pairs naturally with"). Promote a row by confirming the integration and '
            "correcting `jev.jev_role` in the JSON.",
            "",
            "| Repository | Stars | Category | What it does |",
            "|---|---:|---|---|",
        ]
        for key, rec in sorted(listed_only.items(), key=lambda kv: -(kv[1]["stars"] or 0)):
            lines.append(
                f"| [{key}](https://github.com/{key}) | {stars(rec.get('stars'))} | "
                f"{rec['jev']['category']} | {clean(rec.get('desc') or rec.get('gh_desc') or '', 110)} |"
            )
        lines.append("")

    if excluded:
        lines += [
            "---",
            "",
            "## Excluded as unrelated",
            "",
            "Collected from the community lists but classified `not-jev`: sibling "
            "awesome-lists, unrelated tooling, and projects that only share a neighbourhood.",
            "",
            ", ".join(f"`{k}`" for k in sorted(excluded)),
            "",
        ]

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines, {len(verified)} verified entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
