import { execFile } from "node:child_process";
import { constants } from "node:fs";
import { access, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import nodePath from "node:path";

import { afterEach, describe, expect, it } from "vitest";

const packageRoot = process.cwd();
const repoRoot = nodePath.dirname(nodePath.dirname(packageRoot));
const definitionsScript = nodePath.join(repoRoot, "scripts/definitions.ts");
const tsxBin = nodePath.join(repoRoot, "node_modules/.bin/tsx");

const workflowCommandPath = "packages/firehorse-claude/commands/firehorse/diagnose-fix.md";
const skillMirrorPath = "packages/firehorse-claude/skills/firehorse/feedback-loop/SKILL.md";
const maintainerCommandPath = ".claude/commands/release-it.md";
const pluginManifestPath = "packages/firehorse-claude/.claude-plugin/plugin.json";

interface CommandResult {
  readonly exitCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

const tempRepos: string[] = [];

afterEach(async () => {
  await Promise.all(tempRepos.splice(0).map((repo) => rm(repo, { recursive: true, force: true })));
});

// Each case spawns a tsx subprocess, which runs well past vitest's 5s default
// whenever the rest of the suite is competing for CPU.
describe("definitions repository scripts", { timeout: 30_000 }, () => {
  it("reports stale generated mirrors in non-mutating check mode", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const absoluteGeneratedPath = nodePath.join(fixture, workflowCommandPath);
    const generatedContent = await readFile(absoluteGeneratedPath, "utf8");
    const staleContent = generatedContent.replace(
      "Generated by Firehorse. DO NOT EDIT.",
      "Generated by Firehorse. DO NOT EDIT.\nStale test marker.",
    );
    await writeFile(absoluteGeneratedPath, staleContent);

    const checkResult = await runDefinitions(fixture, "--check");

    expect(checkResult.exitCode).toBe(1);
    expect(commandOutput(checkResult)).toContain(`stale generated mirror: ${workflowCommandPath}`);
    await expect(readFile(absoluteGeneratedPath, "utf8")).resolves.toBe(staleContent);
  });

  it("reports missing generated mirrors in check mode and recreates them in write mode", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const absoluteGeneratedPath = nodePath.join(fixture, workflowCommandPath);
    await rm(absoluteGeneratedPath);

    const checkResult = await runDefinitions(fixture, "--check");

    expect(checkResult.exitCode).toBe(1);
    expect(commandOutput(checkResult)).toContain(
      `missing generated mirror: ${workflowCommandPath}`,
    );
    await expect(fileExists(absoluteGeneratedPath)).resolves.toBe(false);

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(`created ${workflowCommandPath}`);
    await expect(fileExists(absoluteGeneratedPath)).resolves.toBe(true);
  });

  it("writes generated manifest entries in deterministic sorted order", async () => {
    const fixture = await createDefinitionsFixture();
    // Written after feedback-loop, and sorting before it, so insertion order cannot pass.
    await writeFile(
      nodePath.join(fixture, "packages/firehorse-core/definitions/skills/alpha-loop.md"),
      minimalSkillDefinition("alpha-loop"),
    );
    await writeFile(
      nodePath.join(fixture, "packages/firehorse-core/definitions/workflows/alpha-fix.md"),
      minimalWorkflowDefinition("alpha-fix"),
    );

    const writeResult = await runDefinitions(fixture, "--write");

    expect(writeResult.exitCode).toBe(0);
    await expect(readJson(nodePath.join(fixture, pluginManifestPath))).resolves.toMatchObject({
      commands: ["./commands/firehorse/alpha-fix.md", "./commands/firehorse/diagnose-fix.md"],
      skills: ["./skills/firehorse/alpha-loop", "./skills/firehorse/feedback-loop"],
    });
  });

  it("reports stale manifests in check mode and repairs them in write mode", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const manifestPath = nodePath.join(fixture, pluginManifestPath);
    const staleManifest = JSON.parse(await readFile(manifestPath, "utf8")) as {
      commands: string[];
      skills: string[];
    };
    staleManifest.skills = ["./skills/firehorse/old-generated"];
    staleManifest.commands = [];
    const staleManifestContent = `${JSON.stringify(staleManifest, null, 2)}\n`;
    await writeFile(manifestPath, staleManifestContent);

    const checkResult = await runDefinitions(fixture, "--check");

    expect(checkResult.exitCode).toBe(1);
    expect(commandOutput(checkResult)).toContain(`stale manifest ${pluginManifestPath}`);
    await expect(readFile(manifestPath, "utf8")).resolves.toBe(staleManifestContent);

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(`updated manifest ${pluginManifestPath}`);
    await expect(readJson(manifestPath)).resolves.toMatchObject({
      commands: ["./commands/firehorse/diagnose-fix.md"],
      skills: ["./skills/firehorse/feedback-loop"],
    });
  });

  it("overwrites provenanced generated mirrors in write mode", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const absoluteGeneratedPath = nodePath.join(fixture, skillMirrorPath);
    const expectedContent = await readFile(absoluteGeneratedPath, "utf8");
    await writeFile(
      absoluteGeneratedPath,
      expectedContent.replace("# Feedback Loop", "# Feedback Loop Drift"),
    );

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(`updated ${skillMirrorPath}`);
    await expect(readFile(absoluteGeneratedPath, "utf8")).resolves.toBe(expectedContent);
  });

  it("deletes stale generated mirrors only when they carry Firehorse provenance", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const provenancedStalePath = "packages/firehorse-claude/commands/firehorse/old-workflow.md";
    const handAuthoredStalePath = "packages/firehorse-claude/commands/firehorse/hand-authored.md";
    const absoluteProvenancedStalePath = nodePath.join(fixture, provenancedStalePath);
    const absoluteHandAuthoredStalePath = nodePath.join(fixture, handAuthoredStalePath);
    const handAuthoredContent = "---\ndescription: Hand authored.\n---\n\n# Hand authored\n";

    await writeFile(
      absoluteProvenancedStalePath,
      await readFile(nodePath.join(fixture, workflowCommandPath), "utf8"),
    );
    await writeFile(absoluteHandAuthoredStalePath, handAuthoredContent);

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(
      `removed stale generated mirror ${provenancedStalePath}`,
    );
    await expect(fileExists(absoluteProvenancedStalePath)).resolves.toBe(false);

    expect(commandOutput(repairResult)).not.toContain(handAuthoredStalePath);
    await expect(readFile(absoluteHandAuthoredStalePath, "utf8")).resolves.toBe(
      handAuthoredContent,
    );
  });

  it("writes a maintainer workflow to .claude/commands and keeps it out of the plugin manifest", async () => {
    const fixture = await createDefinitionsFixture();
    await writeFile(
      nodePath.join(fixture, "packages/firehorse-core/definitions/workflows/release-it.md"),
      minimalWorkflowDefinition("release-it", [], "maintainer"),
    );

    const writeResult = await runDefinitions(fixture, "--write");

    expect(writeResult.exitCode).toBe(0);
    expect(commandOutput(writeResult)).toContain(`created ${maintainerCommandPath}`);
    await expect(fileExists(nodePath.join(fixture, maintainerCommandPath))).resolves.toBe(true);
    await expect(
      fileExists(
        nodePath.join(fixture, "packages/firehorse-claude/commands/firehorse/release-it.md"),
      ),
    ).resolves.toBe(false);

    const manifest = (await readJson(nodePath.join(fixture, pluginManifestPath))) as {
      commands: string[];
    };
    expect(manifest.commands).toEqual(["./commands/firehorse/diagnose-fix.md"]);

    await expect(runDefinitions(fixture, "--check")).resolves.toMatchObject({ exitCode: 0 });
  });

  it("sweeps .claude/commands by provenance when a definition leaves the maintainer audience", async () => {
    const fixture = await createDefinitionsFixture();
    const definitionPath = nodePath.join(
      fixture,
      "packages/firehorse-core/definitions/workflows/release-it.md",
    );
    await writeFile(definitionPath, minimalWorkflowDefinition("release-it", [], "maintainer"));
    expect((await runDefinitions(fixture, "--write")).exitCode).toBe(0);

    const handAuthoredPath = ".claude/commands/hand-authored.md";
    const handAuthoredContent = "---\ndescription: Hand authored.\n---\n\n# Hand authored\n";
    await writeFile(nodePath.join(fixture, handAuthoredPath), handAuthoredContent);

    // Flip the audience: the maintainer mirror is now stale and the user one is new.
    await writeFile(definitionPath, minimalWorkflowDefinition("release-it", [], "user"));
    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(
      `removed stale generated mirror ${maintainerCommandPath}`,
    );
    await expect(fileExists(nodePath.join(fixture, maintainerCommandPath))).resolves.toBe(false);

    // Nothing in .claude/ that Firehorse did not generate is touched.
    expect(commandOutput(repairResult)).not.toContain(handAuthoredPath);
    await expect(readFile(nodePath.join(fixture, handAuthoredPath), "utf8")).resolves.toBe(
      handAuthoredContent,
    );
  });

  it("refuses to overwrite hand-authored generated targets", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const absoluteGeneratedPath = nodePath.join(fixture, skillMirrorPath);
    const manualTargetContent = "# Manual feedback loop\n";
    await writeFile(absoluteGeneratedPath, manualTargetContent);

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(1);
    expect(commandOutput(repairResult)).toContain(
      `refusing to overwrite unprovenanced generated target: ${skillMirrorPath}`,
    );
    await expect(readFile(absoluteGeneratedPath, "utf8")).resolves.toBe(manualTargetContent);
  });
});

/**
 * Builds a throwaway repository carrying its own canonical definitions, so the
 * suite does not depend on any definition checked into this repo.
 */
async function createDefinitionsFixture(): Promise<string> {
  const fixture = await mkdtemp(nodePath.join(os.tmpdir(), "firehorse-definitions-"));
  tempRepos.push(fixture);

  const definitionsRoot = nodePath.join(fixture, "packages/firehorse-core/definitions");
  await mkdir(nodePath.join(definitionsRoot, "workflows"), { recursive: true });
  await mkdir(nodePath.join(definitionsRoot, "skills"), { recursive: true });
  await writeFile(
    nodePath.join(definitionsRoot, "workflows/diagnose-fix.md"),
    minimalWorkflowDefinition("diagnose-fix", ["feedback-loop"]),
  );
  await writeFile(
    nodePath.join(definitionsRoot, "skills/feedback-loop.md"),
    minimalSkillDefinition("feedback-loop"),
  );

  await writeJson(nodePath.join(fixture, "package.json"), {
    name: "firehorse-definitions-fixture",
    private: true,
  });
  await writeJson(nodePath.join(fixture, pluginManifestPath), {
    name: "firehorse-claude-fixture",
    commands: [],
    skills: [],
  });

  return fixture;
}

function titleFor(id: string): string {
  return id
    .split("-")
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(" ");
}

function minimalWorkflowDefinition(
  id: string,
  supportingSkills: readonly string[] = [],
  audience?: "user" | "maintainer",
): string {
  const title = titleFor(id);
  const references =
    supportingSkills.length > 0
      ? `supportingSkills:\n${supportingSkills.map((skill) => `  - id: ${skill}`).join("\n")}\n`
      : "";

  return `---
schemaVersion: 1
id: ${id}
kind: workflow
${audience ? `audience: ${audience}\n` : ""}title: ${title}
description: Minimal generated mirror fixture.
argumentHint: <freeform bug report>
${references}requires:
  tools:
    - read
  environment:
    - filesystem
---

# ${title}

## Purpose

Content.

## Usage

Content.

## Inputs

Content.

## Outputs

Content.

## Supporting Capabilities

Content.

## Orchestration Intent

Content.

## Safety Gates

Content.

## Procedure

Content.

## Projection Notes

Content.
`;
}

function minimalSkillDefinition(id: string): string {
  const title = titleFor(id);

  return `---
schemaVersion: 1
id: ${id}
kind: skill
title: ${title}
description: Minimal generated manifest sorting fixture.
requires:
  tools:
    - read
  environment:
    - filesystem
---

# ${title}

## Purpose

Content.

## Usage

Content.

## Inputs

Content.

## Outputs

Content.

## Instructions

Content.

## Boundaries

Content.

## Examples

Content.

## Projection Notes

Content.
`;
}

async function writeJson(filePath: string, value: unknown): Promise<void> {
  await mkdir(nodePath.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

async function readJson(filePath: string): Promise<unknown> {
  return JSON.parse(await readFile(filePath, "utf8"));
}

async function runDefinitions(cwd: string, mode: "--check" | "--write"): Promise<CommandResult> {
  return new Promise((resolve) => {
    execFile(
      tsxBin,
      [definitionsScript, mode],
      {
        cwd,
        encoding: "utf8",
        env: {
          ...process.env,
          FORCE_COLOR: "0",
        },
      },
      (error, stdout, stderr) => {
        resolve({
          exitCode: typeof error?.code === "number" ? error.code : 0,
          stdout,
          stderr,
        });
      },
    );
  });
}

function commandOutput(result: CommandResult): string {
  return `${result.stdout}\n${result.stderr}`;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}
