import { execFile } from "node:child_process";
import { constants } from "node:fs";
import { access, cp, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import nodePath from "node:path";

import { afterEach, describe, expect, it } from "vitest";

const packageRoot = process.cwd();
const repoRoot = nodePath.dirname(nodePath.dirname(packageRoot));
const definitionsScript = nodePath.join(repoRoot, "scripts/definitions.ts");
const tsxBin = nodePath.join(repoRoot, "node_modules/.bin/tsx");

interface CommandResult {
  readonly exitCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

const tempRepos: string[] = [];

afterEach(async () => {
  await Promise.all(tempRepos.splice(0).map((repo) => rm(repo, { recursive: true, force: true })));
});

describe("definitions repository scripts", () => {
  it("reports stale generated mirrors in non-mutating check mode", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const generatedPath = "packages/firehorse-pi/prompts/firehorse/horse-fix-bug.md";
    const absoluteGeneratedPath = nodePath.join(fixture, generatedPath);
    const generatedContent = await readFile(absoluteGeneratedPath, "utf8");
    const staleContent = generatedContent.replace(
      "Generated by Firehorse. DO NOT EDIT.",
      "Generated by Firehorse. DO NOT EDIT.\nStale test marker.",
    );
    await writeFile(absoluteGeneratedPath, staleContent);

    const checkResult = await runDefinitions(fixture, "--check");

    expect(checkResult.exitCode).toBe(1);
    expect(commandOutput(checkResult)).toContain(`stale generated mirror: ${generatedPath}`);
    await expect(readFile(absoluteGeneratedPath, "utf8")).resolves.toBe(staleContent);
  });

  it("reports missing generated mirrors in check mode and recreates them in write mode", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const generatedPath = "packages/firehorse-claude/commands/firehorse/horse-fix-bug.md";
    const absoluteGeneratedPath = nodePath.join(fixture, generatedPath);
    await rm(absoluteGeneratedPath);

    const checkResult = await runDefinitions(fixture, "--check");

    expect(checkResult.exitCode).toBe(1);
    expect(commandOutput(checkResult)).toContain(`missing generated mirror: ${generatedPath}`);
    await expect(fileExists(absoluteGeneratedPath)).resolves.toBe(false);

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(`created ${generatedPath}`);
    await expect(fileExists(absoluteGeneratedPath)).resolves.toBe(true);
  });

  it("writes generated manifest entries in deterministic sorted order", async () => {
    const fixture = await createDefinitionsFixture();
    await writeFile(
      nodePath.join(fixture, "packages/firehorse-core/definitions/skills/alpha-loop.md"),
      minimalSkillDefinition("alpha-loop"),
    );

    const writeResult = await runDefinitions(fixture, "--write");

    expect(writeResult.exitCode).toBe(0);
    await expect(readJson(nodePath.join(fixture, "package.json"))).resolves.toMatchObject({
      pi: {
        skills: [
          "./packages/firehorse-pi/skills/firehorse/alpha-loop",
          "./packages/firehorse-pi/skills/firehorse/feedback-loop",
          "./packages/firehorse-pi/skills/firehorse/verification-contract",
        ],
      },
    });
    await expect(
      readJson(nodePath.join(fixture, "packages/firehorse-pi/package.json")),
    ).resolves.toMatchObject({
      files: ["extensions", "skills", "prompts", "themes", "agents"],
    });
    await expect(
      readJson(nodePath.join(fixture, "packages/firehorse-claude/.claude-plugin/plugin.json")),
    ).resolves.toMatchObject({
      skills: [
        "./skills/firehorse/alpha-loop",
        "./skills/firehorse/feedback-loop",
        "./skills/firehorse/verification-contract",
      ],
      agents: ["./agents/plan-reviewer.md", "./agents/reviewer.md", "./agents/worker.md"],
    });
  });

  it("reports stale manifests in check mode and repairs them in write mode", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const manifestPath = nodePath.join(fixture, "package.json");
    const staleManifest = JSON.parse(await readFile(manifestPath, "utf8")) as {
      pi: { skills: string[]; prompts: string[] };
    };
    staleManifest.pi.skills = ["./packages/firehorse-pi/skills/firehorse/old-generated"];
    staleManifest.pi.prompts = [];
    const staleManifestContent = `${JSON.stringify(staleManifest, null, 2)}\n`;
    await writeFile(manifestPath, staleManifestContent);

    const checkResult = await runDefinitions(fixture, "--check");

    expect(checkResult.exitCode).toBe(1);
    expect(commandOutput(checkResult)).toContain("stale manifest package.json");
    await expect(readFile(manifestPath, "utf8")).resolves.toBe(staleManifestContent);

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain("updated manifest package.json");
    await expect(readJson(manifestPath)).resolves.toMatchObject({
      pi: {
        skills: [
          "./packages/firehorse-pi/skills/firehorse/feedback-loop",
          "./packages/firehorse-pi/skills/firehorse/verification-contract",
        ],
        prompts: [
          "./packages/firehorse-pi/prompts/firehorse/build.md",
          "./packages/firehorse-pi/prompts/firehorse/fix.md",
          "./packages/firehorse-pi/prompts/firehorse/horse-build.md",
          "./packages/firehorse-pi/prompts/firehorse/horse-create-plan.md",
          "./packages/firehorse-pi/prompts/firehorse/horse-fix-bug.md",
          "./packages/firehorse-pi/prompts/firehorse/horse-new-project.md",
          "./packages/firehorse-pi/prompts/firehorse/horse-plan-review.md",
          "./packages/firehorse-pi/prompts/firehorse/horse-review-code.md",
          "./packages/firehorse-pi/prompts/firehorse/horse-ship.md",
          "./packages/firehorse-pi/prompts/firehorse/horse-update-upstreams.md",
          "./packages/firehorse-pi/prompts/firehorse/plan-review.md",
          "./packages/firehorse-pi/prompts/firehorse/plan-work.md",
          "./packages/firehorse-pi/prompts/firehorse/review.md",
        ],
      },
    });
  });

  it("overwrites provenanced generated mirrors in write mode", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const generatedPath = "packages/firehorse-claude/skills/firehorse/feedback-loop/SKILL.md";
    const absoluteGeneratedPath = nodePath.join(fixture, generatedPath);
    const expectedContent = await readFile(absoluteGeneratedPath, "utf8");
    await writeFile(
      absoluteGeneratedPath,
      expectedContent.replace("# Feedback Loop", "# Feedback Loop Drift"),
    );

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(`updated ${generatedPath}`);
    await expect(readFile(absoluteGeneratedPath, "utf8")).resolves.toBe(expectedContent);
  });

  it("deletes stale generated mirrors only when they carry Firehorse provenance", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const sourcePath = nodePath.join(
      fixture,
      "packages/firehorse-pi/prompts/firehorse/horse-fix-bug.md",
    );
    const stalePath = nodePath.join(
      fixture,
      "packages/firehorse-pi/prompts/firehorse/horse-old-workflow.md",
    );
    await writeFile(stalePath, await readFile(sourcePath, "utf8"));

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(
      "removed stale generated mirror packages/firehorse-pi/prompts/firehorse/horse-old-workflow.md",
    );
    await expect(fileExists(stalePath)).resolves.toBe(false);
  });

  it("reports and removes stale provenanced agent-role mirrors under agents/firehorse", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const sourcePath = nodePath.join(fixture, "packages/firehorse-claude/agents/reviewer.md");
    const staleRelativePath = "packages/firehorse-claude/agents/firehorse/reviewer.md";
    const stalePath = nodePath.join(fixture, staleRelativePath);
    await mkdir(nodePath.dirname(stalePath), { recursive: true });
    await writeFile(stalePath, await readFile(sourcePath, "utf8"));

    const checkResult = await runDefinitions(fixture, "--check");

    expect(checkResult.exitCode).toBe(1);
    expect(commandOutput(checkResult)).toContain(
      `stale generated mirror should be removed: ${staleRelativePath}`,
    );
    await expect(fileExists(stalePath)).resolves.toBe(true);

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(0);
    expect(commandOutput(repairResult)).toContain(
      `removed stale generated mirror ${staleRelativePath}`,
    );
    await expect(fileExists(stalePath)).resolves.toBe(false);
  });

  it("refuses to overwrite hand-authored generated targets", async () => {
    const fixture = await createDefinitionsFixture();
    const writeResult = await runDefinitions(fixture, "--write");
    expect(writeResult.exitCode).toBe(0);

    const generatedPath = "packages/firehorse-pi/skills/firehorse/feedback-loop/SKILL.md";
    const absoluteGeneratedPath = nodePath.join(fixture, generatedPath);
    const manualTargetContent = "# Manual feedback loop\n";
    await writeFile(absoluteGeneratedPath, manualTargetContent);

    const repairResult = await runDefinitions(fixture, "--write");

    expect(repairResult.exitCode).toBe(1);
    expect(commandOutput(repairResult)).toContain(
      `refusing to overwrite unprovenanced generated target: ${generatedPath}`,
    );
    await expect(readFile(absoluteGeneratedPath, "utf8")).resolves.toBe(manualTargetContent);
  });
});

async function createDefinitionsFixture(): Promise<string> {
  const fixture = await mkdtemp(nodePath.join(os.tmpdir(), "firehorse-definitions-"));
  tempRepos.push(fixture);

  await cp(
    nodePath.join(packageRoot, "definitions"),
    nodePath.join(fixture, "packages/firehorse-core/definitions"),
    { recursive: true },
  );
  await mkdir(nodePath.join(fixture, "packages/firehorse-core/upstreams/mattpocock-skills"), {
    recursive: true,
  });
  await writeJson(
    nodePath.join(fixture, "packages/firehorse-core/upstreams/mattpocock-skills/UPSTREAM.json"),
    {
      name: "mattpocock-skills",
      skills: [
        { name: "diagnose" },
        { name: "grill-with-docs" },
        { name: "tdd" },
        { name: "to-issues" },
        { name: "to-prd" },
      ],
    },
  );

  await writeJson(nodePath.join(fixture, "package.json"), {
    name: "firehorse-definitions-fixture",
    private: true,
    pi: {
      skills: [],
      prompts: [],
    },
  });
  await writeJson(nodePath.join(fixture, "packages/firehorse-pi/package.json"), {
    name: "firehorse-pi-fixture",
    files: ["extensions", "skills", "prompts", "themes"],
    pi: {
      skills: [],
      prompts: [],
    },
  });
  await writeJson(nodePath.join(fixture, "packages/firehorse-claude/.claude-plugin/plugin.json"), {
    name: "firehorse-claude-fixture",
    commands: [],
    skills: [],
    agents: [],
  });

  return fixture;
}

function minimalSkillDefinition(id: string): string {
  const title = id
    .split("-")
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(" ");

  return `---
schemaVersion: 1
id: ${id}
kind: skill
title: ${title}
description: Minimal generated manifest sorting fixture.
requires:
  tools:
    - read
  environment:
    - filesystem
---

# ${title}

## Purpose

Content.

## Usage

Content.

## Inputs

Content.

## Outputs

Content.

## Instructions

Content.

## Boundaries

Content.

## Examples

Content.

## Projection Notes

Content.
`;
}

async function writeJson(filePath: string, value: unknown): Promise<void> {
  await mkdir(nodePath.dirname(filePath), { recursive: true });
  await writeFile(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

async function readJson(filePath: string): Promise<unknown> {
  return JSON.parse(await readFile(filePath, "utf8"));
}

async function runDefinitions(cwd: string, mode: "--check" | "--write"): Promise<CommandResult> {
  return new Promise((resolve) => {
    execFile(
      tsxBin,
      [definitionsScript, mode],
      {
        cwd,
        encoding: "utf8",
        env: {
          ...process.env,
          FORCE_COLOR: "0",
        },
      },
      (error, stdout, stderr) => {
        resolve({
          exitCode: typeof error?.code === "number" ? error.code : 0,
          stdout,
          stderr,
        });
      },
    );
  });
}

function commandOutput(result: CommandResult): string {
  return `${result.stdout}\n${result.stderr}`;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}
